version: '3.8'
services:  
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - backend_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: backend

volumes:
  backend_db_data:
